### ISSUE TITLE
Working with Manu document missing

### ISSUE THREAD

**Issue by juanibuqt** [mdb1/mdb1.github.io#1]
Hi Manu! great site, cheers! I was trying to find the document "Working with Manu" without success.

I feel that its important to understand and study better ways of collaboration, in order to have better professional work practices with you, and why not? for other people that want to adopt this philosophy and put everything in a doc, before start a project/work with someone else.

Hope you like this feature request. Keep up the good work! 

J./

**Comment by mdb1** [comment]
Hey @juanibuqt 👋 , thanks for the feedback.
I'll iterate that document and upload it soon 😄

**Comment by mdb1** [comment]
@juanibuqt entry uploaded: https://mdb1.github.io/work/2022/10/29/user-guide-to-working-with-me.html
